name: C/C++ CI

on: [push]

jobs:


  build:
  
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: ubuntu-latest
    timeout-minutes: 1
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make run_tests

